# Generated by Django 4.0.3 on 2022-04-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destinations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destinations',
        ),
    ]
