# Generated by Django 4.0.3 on 2022-04-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_rio_rename_destination_lisbon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lisbon',
        ),
    ]
