# Generated by Django 4.0.3 on 2022-04-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_lisbon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rio',
            new_name='Places',
        ),
    ]
