# Generated by Django 4.0.3 on 2022-04-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_rename_rio_places'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lisbon',
        ),
    ]
