# Generated by Django 4.0.3 on 2022-04-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Address',
            new_name='Con_Password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='Con_Address',
            new_name='Password',
        ),
    ]
