# Generated by Django 4.0.3 on 2022-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_rename_address_signup_con_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Phone',
            field=models.IntegerField(default=4238546235),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Con_Password',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Password',
            field=models.CharField(max_length=18),
        ),
    ]
