# Generated by Django 4.0.3 on 2022-04-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_signup_phone_alter_signup_con_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Phone',
        ),
    ]
