# Generated by Django 4.0.3 on 2022-04-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_signup_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Phone',
        ),
    ]
