# Generated by Django 4.0.3 on 2022-04-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0020_remove_signup_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
