# Generated by Django 4.0.3 on 2022-04-27 20:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0022_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
