# Generated by Django 4.0.3 on 2022-04-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0024_placeyear_alter_signup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
    ]
