# Generated by Django 4.0.3 on 2022-04-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0025_alter_signup_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeyear',
            name='Image',
            field=models.ImageField(default=0, upload_to='pics'),
        ),
    ]
