# Generated by Django 4.0.3 on 2022-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0028_remove_placeyear_count_placeyear_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeyear',
            old_name='offer',
            new_name='Offer',
        ),
        migrations.AddField(
            model_name='placeyear',
            name='Country',
            field=models.TextField(default=1),
        ),
    ]
