# Generated by Django 4.0.3 on 2022-05-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0029_rename_offer_placeyear_offer_placeyear_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeyear',
            name='Country',
            field=models.CharField(max_length=30),
        ),
    ]
