# Generated by Django 4.0.3 on 2022-05-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0030_alter_placeyear_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Con_Password',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='Lastname',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='Password',
        ),
    ]
