# Generated by Django 4.0.3 on 2022-05-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0031_remove_signup_con_password_remove_signup_firstname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceYear',
        ),
    ]
