# Generated by Django 4.0.3 on 2022-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0033_remove_places_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='country',
            field=models.TextField(default=1),
        ),
    ]
