# Generated by Django 4.0.3 on 2022-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0034_places_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
