# Generated by Django 4.0.3 on 2022-05-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0035_alter_places_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='offer',
            new_name='interests',
        ),
        migrations.AddField(
            model_name='places',
            name='top_place',
            field=models.BooleanField(default=False),
        ),
    ]
