# Generated by Django 4.0.3 on 2022-05-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0036_rename_offer_places_interests_places_top_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='name',
            new_name='capital',
        ),
    ]
