# Generated by Django 4.0.3 on 2022-05-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0037_rename_name_places_capital'),
    ]

    operations = [
        migrations.CreateModel(
            name='sdjh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
    ]
