# Generated by Django 4.0.3 on 2022-05-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0038_sdjh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sdjh',
        ),
    ]
