# Generated by Django 4.0.3 on 2022-05-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0041_places_continent_places_currency_places_population_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='continent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='places',
            name='currency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='places',
            name='population',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='places',
            name='president',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='places',
            name='square',
            field=models.CharField(max_length=100),
        ),
    ]
