# Generated by Django 4.0.3 on 2022-05-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0043_places_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='flag',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
