# Generated by Django 4.0.3 on 2022-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0045_alter_places_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='province',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
