# Generated by Django 4.0.3 on 2022-05-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0046_places_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='province',
            field=models.IntegerField(default=0),
        ),
    ]
