# Generated by Django 4.0.3 on 2022-05-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0047_alter_places_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='province',
            field=models.IntegerField(),
        ),
    ]
