# Generated by Django 4.0.3 on 2022-05-11 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0048_alter_places_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2022, 5, 11, 15, 57, 18, 588040, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='srch',
        ),
    ]
