# Generated by Django 4.0.3 on 2022-05-12 22:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0050_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='CKeditor test'),
        ),
        migrations.AlterField(
            model_name='places',
            name='flag',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='places',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
