# Generated by Django 4.0.3 on 2022-05-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0051_places_content_alter_places_flag_alter_places_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='content',
        ),
    ]
