# Generated by Django 4.0.3 on 2022-05-12 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0052_remove_places_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='places',
            name='flag',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='places',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travello.property')),
            ],
        ),
    ]
