# Generated by Django 4.0.3 on 2022-05-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0053_property_alter_places_flag_alter_places_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travello.places'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
