# Generated by Django 4.0.3 on 2022-05-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0054_alter_propertyimage_property_delete_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='img',
        ),
    ]
