# Generated by Django 4.0.3 on 2022-05-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0056_alter_propertyimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.CharField(max_length=9999),
        ),
    ]
