# Generated by Django 4.0.3 on 2022-05-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0059_alter_places_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=9999)),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travello.places')),
            ],
        ),
    ]
