# Generated by Django 4.0.3 on 2022-05-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0066_alter_places_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='province',
            field=models.CharField(max_length=10),
        ),
    ]
