# Generated by Django 4.0.3 on 2022-05-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0070_alter_places_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='province',
        ),
    ]
